server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/selectstarfrom/liv-ecom-config.git}
          username: ${CONFIG_REPO_USER:}
          password: ${CONFIG_REPO_PASS:}
          default-label: main
          search-paths: /
          clone-on-start: true
          force-pull: true
app.test: cloud
