server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/selectstarfrom/taskettan.git}
          username: ${CONFIG_REPO_USER:}
          password: ${CONFIG_REPO_PASS:}
          default-label: dev-docker
          search-paths: liv-ecom-config-server/src/main/resources/config-repo
          clone-on-start: true
          force-pull: true
